export const defaultDSLConfig = ({
  id: '75f0extui9d7yksklx27hff8xg',
  name: 'test',
  type: 'app',
  items: [
    {
      type: 'page',
      id: 'page_299',
      name: 'index',
      title: '',
      layout: 'absolute',
      style: {
        position: 'relative',
        left: 0,
        top: 0,
        right: '',
        bottom: '',
        width: '1024',
        height: '600',
        backgroundImage: '',
        backgroundColor: '#ECEDFA',
        backgroundRepeat: 'no-repeat',
        backgroundSize: '100% 100%',
        color: '',
        fontSize: '',
        fontWeight: '',
      },
      events: [],
      created: '',
      items: [
        {
          id: 'qrcode_37ddc840',
          type: 'qrcode',
          style: {
            position: 'absolute',
            left: '57',
            width: '176',
            height: '176',
            top: '212',
          },
          name: '二维码',
          url: 'https://m.film.qq.com',
        },
      ],
    },
  ],
});
