/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContentMenu: typeof import('./src/components/ContentMenu.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    ScrollBar: typeof import('./src/components/ScrollBar.vue')['default']
    ScrollViewer: typeof import('./src/components/ScrollViewer.vue')['default']
    ToolButton: typeof import('./src/components/ToolButton.vue')['default']
  }
}
